services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    cap_add:
      - NET_ADMIN
    container_name: caddy
    hostname: caddy
    environment:
      - CADDY_INGRESS_NETWORKS=opencloud-compose_opencloud-net
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /mnt/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /mnt/docker/caddy/site:/srv
      - /mnt/docker/caddy/data:/data
      - /mnt/docker/caddy/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      opencloud-net: null
networks:
  opencloud-net:
    name: opencloud-compose_opencloud-net
volumes:
  data:
  config:
  site:
