---
services:
  tika:
    image: ${TIKA_IMAGE:-apache/tika:latest}
    # Using the base variant for smaller image size and faster startup
    # The base variant includes core functionality for text extraction
    # Full variant is only needed for specialized OCR/image processing
    # release notes: https://tika.apache.org
    networks:
      opencloud-net:
    restart: always
    logging:
      driver: ${LOG_DRIVER:-local}
    healthcheck:
      test: >
        bash -c "exec 3<>/dev/tcp/localhost/9998 &&
        printf 'GET /tika HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 &&
        head -n1 <&3 | grep -qE '200 OK'"
      start_period: 10s
      interval: 15s
      timeout: 5s
      retries: 3

  opencloud:
    environment:
      # fulltext search
      SEARCH_EXTRACTOR_TYPE: tika
      SEARCH_EXTRACTOR_TIKA_TIKA_URL: http://tika:9998
      FRONTEND_FULL_TEXT_SEARCH_ENABLED: "true"
