---
services:
  opencloud:
    environment:
      POSTPROCESSING_STEPS: "virusscan"
      STORAGE_USERS_DATA_GATEWAY_URL: "http://opencloud:9200/data"
      ANTIVIRUS_MAX_SCAN_SIZE: ${ANTIVIRUS_MAX_SCAN_SIZE:-100MB}
      ANTIVIRUS_INFECTED_FILE_HANDLING: abort
      ANTIVIRUS_MAX_SCAN_SIZE_MODE: ${ANTIVIRUS_MAX_SCAN_SIZE_MODE:-partial}
      ANTIVIRUS_WORKERS: 1
      ANTIVIRUS_CLAMAV_SOCKET: /var/run/clamav/clamd.sock
      ANTIVIRUS_SCANNER_TYPE: clamav
    volumes:
      - clamav-socket:/var/run/clamav
  clamav:
    image: clamav/clamav:${CLAMAV_DOCKER_TAG:-latest}
    environment:
      # Accepts a number with optional K, M or G suffix. Must be greater or equal to ANTIVIRUS_MAX_SCAN_SIZE above.
      # K = KiB (1024), M = MiB (1024 * 1024), G = GiB (1024 * 1024 * 1024)
      CLAMD_CONF_StreamMaxLength: 100M
    networks:
      opencloud-net:
    volumes:
      - clamav-socket:/tmp
      - clamav-db:/var/lib/clamav
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always
volumes:
  clamav-db:
  clamav-socket:
